import random,re
from typing import Dict, Any, List
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

# -------------------------
# Training data (from your examples)
# -------------------------

TRAINING_DATA = {
  "property_lookup": [
    "What is the hardness of diamond?",
    "Give me the yield strength of stainless steel.",
    "Show me the thermal conductivity of copper.",
    "Tell me the density of aluminum.",
    "Elastic modulus of titanium?",
    "Poisson’s ratio of glass?",
    "Provide melting point of iron.",
    "Band gap of silicon?",
    "Refractive index of diamond?",
    "Corrosion rate of zinc in seawater?",
    "What is the compressive strength of concrete?",
    "Give me the tensile strength of carbon fiber.",
    "What is the dielectric constant of silicon dioxide?",
    "Specific heat capacity of copper?",
    "Lattice constant of germanium?",
    "Thermal expansion coefficient of aluminum?",
    "Hardness of tungsten carbide?",
    "What is the resistivity of silver?",
    "Give me density of lead.",
    "Young’s modulus of steel?",
    "Fracture toughness of ceramics?",
    "What is band gap of GaAs?",
    "Provide magnetic susceptibility of iron.",
    "Give me hardness of quartz.",
    "Thermal conductivity of diamond?",
    "What is Poisson’s ratio of rubber?",
    "Melting point of sodium chloride?",
    "Elastic modulus of copper?",
    "Bulk modulus of steel?",
    "Thermal diffusivity of aluminum?",
    "Dielectric strength of mica?",
    "Hardness of sapphire?",
    "Density of magnesium?",
    "What is refractive index of water?",
    "Specific gravity of gold?",
    "Give me fatigue strength of titanium.",
    "Creep resistance of nickel?",
    "Thermal conductivity of brass?",
    "Shear modulus of glass?",
    "What is hardness of obsidian?",
    "Provide electrical conductivity of copper.",
    "What is thermal expansion of steel?",
    "Melting temperature of tungsten?",
    "What is density of silicon?",
    "Band gap of gallium nitride?",
    "Refractive index of sapphire?",
    "Hardness of boron nitride?",
    "What is strength of graphene?",
    "Thermal conductivity of silver?",
    "Dielectric constant of Teflon?",
    "Magnetization of cobalt?",
    "Provide density of uranium.",
    "Tensile strength of Kevlar?",
    "Elastic modulus of diamond?",
    "Poisson’s ratio of steel?",
    "Corrosion resistance of stainless steel?",
    "Thermal conductivity of ceramic?",
    "Fracture toughness of glass?",
    "Shear strength of copper?",
    "Density of brass?",
    "Resistivity of graphite?",
    "What is band gap of CdTe?",
    "Specific heat of aluminum?",
    "Thermal expansion of concrete?",
    "Compressive strength of granite?",
    "Young’s modulus of aluminum?",
    "Hardness of lead?",
    "Magnetic permeability of iron?",
    "Electrical resistivity of silicon?",
    "Dielectric loss tangent of glass?",
    "Thermal conductivity of polymer?",
    "What is density of ice?",
    "Give me lattice parameter of silicon.",
    "Fracture toughness of steel?",
    "Elastic modulus of glass fiber?",
    "Hardness of copper?",
    "Bulk modulus of diamond?",
    "Thermal conductivity of beryllium?",
    "What is refractive index of acrylic?",
    "Poisson’s ratio of concrete?",
    "Yield strength of bronze?",
    "Specific heat of iron?",
    "Hardness of zirconia?",
    "Thermal conductivity of graphite?",
    "Density of zinc?",
    "Shear modulus of aluminum?",
    "Electrical conductivity of gold?",
    "What is melting point of glass?",
    "Dielectric constant of paper?",
    "Fracture toughness of aluminum oxide?",
    "Magnetic susceptibility of nickel?",
    "Thermal conductivity of superconductor?",
    "Elastic modulus of polymer?",
    "What is hardness of basalt?",
    "Provide compressive strength of ice.",
    "Thermal expansion of copper?",
    "Resistivity of platinum?",
    "Density of wood?",
    "Band gap of perovskite?",
    "Tensile strength of steel wire?"
  ],
  "comparison": [
    "Compare steel and aluminum strength.",
    "Which is lighter, titanium or magnesium?",
    "Show me thermal conductivity of copper vs silver.",
    "Is glass harder than plastic?",
    "Compare melting points of gold and platinum.",
    "Which alloy is better for high temperature, Inconel or stainless steel?",
    "Copper vs aluminum: better conductor?",
    "Compare hardness of diamond and cubic boron nitride.",
    "Which has higher refractive index, diamond or sapphire?",
    "Compare density of steel and concrete.",
    "Titanium vs aluminum: which is stronger?",
    "Compare tensile strength of Kevlar and carbon fiber.",
    "Which metal is more ductile, gold or copper?",
    "Compare yield strength of brass vs bronze.",
    "Is silicon more conductive than germanium?",
    "Compare thermal expansion of glass vs steel.",
    "Which is more corrosion resistant, stainless steel or titanium?",
    "Compare specific heat of water vs ethanol.",
    "Which has higher band gap, GaAs or GaN?",
    "Compare compressive strength of granite and marble.",
    "Is sapphire harder than quartz?",
    "Compare fracture toughness of aluminum vs steel.",
    "Which is lighter, carbon fiber or aluminum?",
    "Compare magnetic permeability of iron and nickel.",
    "Is graphene stronger than diamond?",
    "Compare density of copper and lead.",
    "Which is better conductor, silver or copper?",
    "Compare hardness of tungsten vs titanium.",
    "Is platinum denser than gold?",
    "Compare elasticity of rubber vs steel.",
    "Which melts first, aluminum or zinc?",
    "Compare creep resistance of nickel alloy vs steel.",
    "Is zirconia harder than alumina?",
    "Compare band gap of silicon vs perovskite.",
    "Which has higher refractive index, glass or diamond?",
    "Compare shear strength of steel vs titanium.",
    "Is magnesium lighter than lithium?",
    "Compare conductivity of graphite vs diamond.",
    "Which metal is more malleable, silver or copper?",
    "Compare fatigue resistance of steel vs aluminum.",
    "Is diamond stronger than boron nitride?",
    "Compare heat capacity of copper vs aluminum.",
    "Which expands more, brass or iron?",
    "Compare resistivity of gold and silver.",
    "Is nylon stronger than polyester?",
    "Compare corrosion of zinc vs magnesium.",
    "Which has higher melting point, tungsten or molybdenum?",
    "Compare ductility of lead vs tin.",
    "Is concrete denser than brick?",
    "Compare transparency of glass vs acrylic.",
    "Which is tougher, steel or titanium?",
    "Compare density of mercury vs lead.",
    "Is alumina harder than quartz?",
    "Compare oxidation resistance of nickel vs chromium.",
    "Which is more flexible, copper or steel?",
    "Compare brittleness of glass vs ceramic.",
    "Is graphene lighter than aluminum?",
    "Compare thermal conductivity of brass vs bronze.",
    "Which has higher hardness, sapphire or ruby?",
    "Compare compressive strength of concrete vs steel.",
    "Is diamond denser than graphite?",
    "Compare elasticity of nylon vs Kevlar.",
    "Which alloy resists rust better, stainless steel or mild steel?",
    "Compare tensile strength of iron vs copper.",
    "Is beryllium lighter than magnesium?",
    "Compare fracture strength of silicon vs glass.",
    "Which is stronger, tungsten or titanium?",
    "Compare heat resistance of Inconel vs stainless steel.",
    "Is basalt harder than granite?",
    "Compare malleability of aluminum vs lead.",
    "Which has better creep resistance, steel or copper?",
    "Compare toughness of Kevlar vs carbon fiber.",
    "Is silver more conductive than gold?",
    "Compare band gap of CdTe vs GaAs.",
    "Which is more transparent, acrylic or polycarbonate?",
    "Compare hardness of brass vs bronze.",
    "Is magnesium stronger than aluminum?",
    "Compare specific gravity of iron vs steel.",
    "Which has higher dielectric constant, mica or glass?",
    "Compare melting point of steel vs iron.",
    "Is platinum more corrosion resistant than palladium?",
    "Compare density of zinc vs tin.",
    "Which is more flexible, copper or gold?",
    "Compare refractive index of water vs oil.",
    "Is tungsten denser than uranium?",
    "Compare thermal expansion of diamond vs graphite.",
    "Which alloy is stronger, bronze or brass?",
    "Compare fracture toughness of ceramics vs polymers.",
    "Is steel more magnetic than cobalt?",
    "Compare hardness of obsidian vs quartz.",
    "Which has higher compressive strength, ice or wood?",
    "Compare fatigue limit of steel vs brass.",
    "Is gold heavier than mercury?",
    "Compare strength of bamboo vs wood.",
    "Which is harder, ruby or sapphire?",
    "Compare ductility of copper vs aluminum."
  ],
  "prediction": [
    "Will aluminum corrode in seawater?",
    "Predict fatigue life of titanium alloy.",
    "How will copper behave under cyclic loading?",
    "Estimate lifetime of steel in acidic environment.",
    "Will stainless steel rust in coastal areas?",
    "Predict dielectric breakdown in ceramics.",
    "How long will polyethylene last under UV exposure?",
    "Forecast creep in nickel superalloys.",
    "Estimate corrosion resistance of magnesium alloy.",
    "Will glass shatter under thermal shock?",
    "Predict oxidation of aluminum at high temperature.",
    "How will concrete behave in freezing conditions?",
    "Estimate service life of plastic pipes underground.",
    "Will brass tarnish in humid air?",
    "Predict durability of graphene composites.",
    "How long will lithium batteries last in storage?",
    "Forecast degradation of polymers under heat.",
    "Will steel lose strength in fire?",
    "Predict crack growth in ceramics.",
    "How will magnesium corrode in salt water?",
    "Estimate fatigue cycles of steel beams.",
    "Will copper wires oxidize outdoors?",
    "Predict breakdown of capacitor dielectric.",
    "How long will stainless steel stay shiny?",
    "Forecast wear of cutting tools.",
    "Will rubber crack under sunlight?",
    "Predict corrosion in reinforced concrete.",
    "How will carbon fiber age under stress?",
    "Estimate service life of asphalt.",
    "Will iron rust faster in rain or seawater?",
    "Predict strength loss in plastics over time.",
    "How will ceramics respond to impact?",
    "Estimate lifetime of LED materials.",
    "Will titanium resist acid corrosion?",
    "Predict fracture in glass under load.",
    "How long will wood last untreated outdoors?",
    "Forecast creep of polymers at high temp.",
    "Will silicon degrade under radiation?",
    "Predict erosion of turbine blades.",
    "How will alloys behave at cryogenic temps?",
    "Estimate fatigue strength of weld joints.",
    "Will polyethylene pipes crack with age?",
    "Predict color fading of polymers in UV.",
    "How long will steel bridges last?",
    "Forecast corrosion of ship hulls.",
    "Will concrete absorb CO2 long-term?",
    "Predict lifespan of solar panel glass.",
    "How will zirconia behave in fuel cells?",
    "Estimate wear in bearings.",
    "Will graphite electrodes last in arc furnace?",
    "Predict heat damage in polymers.",
    "How long will bronze statues last outdoors?",
    "Forecast rusting of nails.",
    "Will nickel alloys survive jet engines?",
    "Predict strength loss in aged composites.",
    "How will asphalt soften under heat?",
    "Estimate degradation rate of plastics in ocean.",
    "Will glass fiber composites degrade?",
    "Predict lifespan of aluminum roofing.",
    "How long will paper last in storage?",
    "Forecast wear in gear steel.",
    "Will zinc coatings last in rain?",
    "Predict crack growth in polymers.",
    "How will metals respond to fatigue?",
    "Estimate rust rate of mild steel.",
    "Will diamond tools wear out?",
    "Predict long-term creep of concrete.",
    "How long will ceramics last in reactors?",
    "Forecast corrosion in pipelines.",
    "Will stainless steel survive seawater?",
    "Predict swelling in polymers.",
    "How will copper alloys resist tarnish?",
    "Estimate service life of steel cables.",
    "Will glass lenses degrade in UV?",
    "Predict hydrogen embrittlement in steel.",
    "How long will coatings last outdoors?",
    "Forecast erosion in wind turbines.",
    "Will rubbers degrade in ozone?",
    "Predict fatigue damage in composites.",
    "How will gold resist corrosion?",
    "Estimate lifespan of medical implants.",
    "Will titanium corrode in body fluids?",
    "Predict wear in machine tools.",
    "How long will insulation foam last?",
    "Forecast cracking of ceramics.",
    "Will aluminum alloys deform under load?",
    "Predict weathering of wood.",
    "How will polymers behave in radiation?",
    "Estimate lifespan of plastic bottles.",
    "Will stainless steel resist chlorine?",
    "Predict scaling in boilers.",
    "How long will graphite rods last?",
    "Forecast degradation of paints.",
    "Will brass corrode in salt spray?",
    "Predict rust in old cars.",
    "How will glass age over centuries?",
    "Estimate fatigue of aircraft alloys."
  ],
  "theory_explain": [
    "Explain phase diagrams.",
    "What is crystallography?",
    "Describe matter waves.",
    "Explain energy bands in semiconductors.",
    "What is diffusion in solids?",
    "Explain thermodynamics of phase change.",
    "Describe kinetics of grain growth.",
    "What is polymer rheology?",
    "Explain glass formation.",
    "What is dislocation theory?",
    "Explain creep mechanism in metals.",
    "Describe superconductivity.",
    "What is quantum tunneling?",
    "Explain fracture mechanics.",
    "Describe fatigue process.",
    "What is magnetism in materials?",
    "Explain electron mobility.",
    "Describe chemical bonding in solids.",
    "What is solid solution strengthening?",
    "Explain alloy phase transformations.",
    "Describe diffusion bonding.",
    "What is Hall effect?",
    "Explain p-n junction theory.",
    "Describe plastic deformation.",
    "What is elastic deformation?",
    "Explain X-ray diffraction.",
    "Describe electron microscopy.",
    "What is corrosion science?",
    "Explain surface energy.",
    "Describe nucleation and growth.",
    "What is amorphous solid?",
    "Explain glass transition temperature.",
    "Describe hardness mechanism.",
    "What is ionic bonding?",
    "Explain metallic bonding.",
    "Describe van der Waals forces.",
    "What is spintronics?",
    "Explain density functional theory.",
    "Describe electronic band gap.",
    "What is ferroelectricity?",
    "Explain piezoelectricity.",
    "Describe magnetic domains.",
    "What is anisotropy?",
    "Explain isotropy in materials.",
    "Describe viscoelasticity.",
    "What is fracture toughness?",
    "Explain Griffith theory of cracks.",
    "Describe wear mechanisms.",
    "What is adhesion?",
    "Explain wetting phenomena.",
    "Describe catalysis in materials.",
    "What is semiconductor doping?",
    "Explain carrier concentration.",
    "Describe excitons.",
    "What is phonon scattering?",
    "Explain thermal conductivity theory.",
    "Describe electrical resistivity.",
    "What is superconducting gap?",
    "Explain Josephson effect.",
    "Describe thermoelectric effect.",
    "What is magnetoresistance?",
    "Explain hysteresis loop.",
    "Describe magnetic hysteresis loss.",
    "What is crystallographic texture?",
    "Explain slip systems.",
    "Describe twin boundaries.",
    "What is point defect?",
    "Explain vacancy diffusion.",
    "Describe interstitial diffusion.",
    "What is substitutional solid solution?",
    "Explain grain boundary diffusion.",
    "Describe precipitation hardening.",
    "What is spin glass?",
    "Explain magnetic susceptibility.",
    "Describe optical absorption.",
    "What is photoluminescence?",
    "Explain stimulated emission.",
    "Describe laser action.",
    "What is solidification?",
    "Explain casting defects.",
    "Describe dendritic growth.",
    "What is heat treatment?",
    "Explain annealing.",
    "Describe quenching.",
    "What is tempering?",
    "Explain sintering.",
    "Describe powder metallurgy.",
    "What is composite material theory?",
    "Explain fiber-matrix bonding.",
    "Describe fracture in composites.",
    "What is self-healing material?",
    "Explain smart material behavior.",
    "Describe shape memory alloys.",
    "What is nanomaterial behavior?"
  ],
  "process_guidance": [
    "How is glass manufactured?",
    "Process of making steel.",
    "Explain aluminum extrusion.",
    "How is welding done?",
    "Process of 3D printing metals.",
    "How are ceramics sintered?",
    "How to temper glass?",
    "Process of making carbon fiber.",
    "How is cement produced?",
    "Explain casting process.",
    "How is forging carried out?",
    "Steps in powder metallurgy.",
    "How is annealing performed?",
    "Process of rolling steel.",
    "How to make composites?",
    "Explain polymer extrusion.",
    "How is plastic injection molding done?",
    "Steps in semiconductor fabrication.",
    "How is glass blowing done?",
    "Explain carburizing process.",
    "How is quenching performed?",
    "Process of tempering steel.",
    "How is recycling done?",
    "Steps in additive manufacturing.",
    "How to make Kevlar fibers?",
    "Explain electroplating process.",
    "How is anodizing done?",
    "Process of vacuum deposition.",
    "How is sputtering performed?",
    "Steps in thin film coating.",
    "How is cement hydrated?",
    "Explain hydration of gypsum.",
    "How to weld aluminum?",
    "Steps in brazing.",
    "How is soldering done?",
    "Explain reflow soldering.",
    "Process of hot isostatic pressing.",
    "How is powder compaction done?",
    "Explain mechanical alloying.",
    "How is diffusion bonding carried out?",
    "Steps in laser cutting.",
    "How is water jet cutting done?",
    "Process of machining.",
    "Explain CNC milling.",
    "How is drilling carried out?",
    "Steps in heat treatment.",
    "How is surface hardening done?",
    "Explain nitriding process.",
    "How to coat with PVD?",
    "Steps in CVD process.",
    "How is graphene synthesized?",
    "Explain chemical vapor deposition.",
    "Process of molecular beam epitaxy.",
    "How is nanomaterial fabricated?",
    "Steps in electrospinning.",
    "How is fiber drawn?",
    "Explain sol-gel process.",
    "How is aerogel made?",
    "Steps in glass tempering.",
    "How is polymer cured?",
    "Process of vulcanization.",
    "How is paper manufactured?",
    "Explain pulping process.",
    "How is wood laminated?",
    "Steps in making plywood.",
    "How is ceramic glazing done?",
    "Process of firing pottery.",
    "How is enamel applied?",
    "Explain sintering ceramics.",
    "How is brick made?",
    "Steps in concrete mixing.",
    "How is asphalt prepared?",
    "Process of galvanization.",
    "How is steel coated?",
    "Explain powder coating.",
    "How is paint applied industrially?",
    "Steps in spray coating.",
    "How is lamination done?",
    "Process of vacuum forming.",
    "How is thermoforming performed?",
    "Explain blow molding.",
    "How is fiber reinforced plastic made?",
    "Steps in resin transfer molding.",
    "How is additive layer manufactured?",
    "Process of selective laser sintering.",
    "How is electron beam welding done?",
    "Steps in plasma cutting.",
    "How is arc welding carried out?",
    "Explain MIG welding.",
    "How is TIG welding performed?",
    "Process of shielded metal arc welding.",
    "How is friction stir welding done?",
    "Steps in ultrasonic welding.",
    "How is spot welding performed?",
    "Explain resistance welding.",
    "How is metal casting carried out?"
  ],
  "news_request": [
    "Show me latest research in materials science.",
    "What are new technologies in steel making?",
    "Any innovations in glass?",
    "Give me recent news on nanomaterials.",
    "Latest advances in biomaterials?",
    "What’s trending in superconductors?",
    "Show me articles on recycling.",
    "Give updates about battery technology.",
    "Any breakthroughs in graphene research?",
    "What’s new in quantum materials?",
    "Show me developments in 3D printing metals.",
    "Latest discoveries in ceramics?",
    "Any updates in semiconductor industry?",
    "What’s new in plastic recycling?",
    "Show me research on smart materials.",
    "Latest news on composites?",
    "What’s trending in aerospace materials?",
    "Any innovation in biodegradable plastics?",
    "Show me new metal alloys research.",
    "Latest findings on carbon nanotubes?",
    "What’s new in perovskite solar cells?",
    "Show me research on hydrogen storage.",
    "Latest discoveries in magnetic materials?",
    "Any updates on superconducting wires?",
    "What’s trending in structural materials?",
    "Show me recent research on coatings.",
    "Latest developments in polymers?",
    "Any new technologies in cement?",
    "What’s new in additive manufacturing?",
    "Show me breakthroughs in solid-state batteries.",
    "Latest news on recycling glass?",
    "Any progress in lithium-ion batteries?",
    "What’s new in biomimetic materials?",
    "Show me recent advances in nanotechnology.",
    "Latest research on surface engineering?",
    "Any updates in energy storage materials?",
    "What’s trending in medical implants?",
    "Show me news on corrosion prevention.",
    "Latest discoveries in photovoltaics?",
    "Any innovations in wind turbine materials?",
    "What’s new in construction materials?",
    "Show me progress in aerospace composites.",
    "Latest updates on rare earth metals?",
    "Any research on transparent ceramics?",
    "What’s trending in fuel cell materials?",
    "Show me news about plastic upcycling.",
    "Latest research on catalysts?",
    "Any updates in metallurgy?",
    "What’s new in nanoelectronics?",
    "Show me research on biodegradable metals.",
    "Latest discoveries in quantum dots?",
    "Any news in superconducting magnets?",
    "What’s trending in green materials?",
    "Show me updates in recycling steel.",
    "Latest research in thin films?",
    "Any innovations in wearable materials?",
    "What’s new in flexible electronics?",
    "Show me discoveries in polymer science.",
    "Latest news in construction steel?",
    "Any updates in ceramic membranes?",
    "What’s trending in photonic materials?",
    "Show me progress in biomaterials.",
    "Latest research on shape memory alloys?",
    "Any innovations in transparent polymers?",
    "What’s new in aerospace alloys?",
    "Show me recent discoveries in metallurgy.",
    "Latest news in corrosion resistant coatings?",
    "Any research on high entropy alloys?",
    "What’s trending in biomedical nanomaterials?",
    "Show me updates in perovskite LEDs.",
    "Latest progress in hydrogen fuel cells?",
    "Any discoveries in smart coatings?",
    "What’s new in construction composites?",
    "Show me news about polymer recycling.",
    "Latest research in superconductivity?",
    "Any updates in solid oxide fuel cells?",
    "What’s trending in biodegradable polymers?",
    "Show me progress in rare metal recycling.",
    "Latest updates in semiconductor packaging?",
    "Any new findings in carbon capture materials?",
    "What’s new in thermal barrier coatings?",
    "Show me advances in self-healing materials.",
    "Latest news in aerogels?",
    "Any research on nuclear materials?",
    "What’s trending in transparent electrodes?",
    "Show me progress in advanced ceramics.",
    "Latest findings in nanocomposites?",
    "Any updates in dielectric materials?",
    "What’s new in energy harvesting materials?",
    "Show me research on flexible batteries.",
    "Latest news on polymer blends?",
    "Any progress in corrosion inhibitors?",
    "What’s trending in graphene sensors?",
    "Show me advances in superconducting films.",
    "Latest discoveries in bioinspired materials?",
    "Any innovations in fiber optics?",
    "What’s new in concrete technology?",
    "Show me breakthroughs in thin-film solar cells."
  ],
  "casual_chat": [
    "Hello MatBot!",
    "Hi there.",
    "How are you?",
    "Tell me a joke.",
    "What can you do?",
    "You are smart.",
    "Thanks.",
    "Goodbye.",
    "See you later.",
    "Hey!",
    "What’s up?",
    "Yo MatBot!",
    "Nice to meet you.",
    "How’s your day?",
    "Long time no see.",
    "Good morning!",
    "Good night.",
    "Bye.",
    "Take care.",
    "Talk to you soon.",
    "MatBot, are you there?",
    "What’s your name?",
    "Can you help me?",
    "I like you.",
    "You’re funny.",
    "That was cool.",
    "Amazing!",
    "Great job.",
    "Well done.",
    "See you tomorrow.",
    "Catch you later.",
    "Thanks a lot.",
    "You rock.",
    "Cool!",
    "Interesting.",
    "Tell me something fun.",
    "What do you know?",
    "Do you like science?",
    "I’m bored.",
    "Cheer me up.",
    "Tell me a fact.",
    "That’s awesome.",
    "You’re cool.",
    "I need a friend.",
    "Tell me more.",
    "Good to see you.",
    "I missed you.",
    "You’re helpful.",
    "Let’s chat.",
    "Are you smart?",
    "Tell me something new.",
    "That’s funny.",
    "I trust you.",
    "Nice answer.",
    "You are kind.",
    "Can you joke again?",
    "MatBot is the best!",
    "I enjoy this chat.",
    "That’s cool.",
    "I love this bot.",
    "Superb!",
    "Awesome stuff.",
    "Really nice.",
    "Sweet!",
    "Thanks buddy.",
    "I’m impressed.",
    "Brilliant!",
    "Good chat.",
    "Great help.",
    "Wonderful.",
    "Nice work.",
    "Pretty cool.",
    "I’m glad.",
    "That was fun.",
    "MatBot rocks!",
    "You’re awesome.",
    "Keep it up.",
    "Respect.",
    "Very cool.",
    "Haha, funny.",
    "I laughed.",
    "So good.",
    "Impressive.",
    "That’s nice.",
    "Excellent.",
    "I feel good.",
    "Cool bot.",
    "Great friend.",
    "So helpful.",
    "I like chatting.",
    "MatBot is awesome.",
    "Really funny.",
    "Good vibe.",
    "Super helpful.",
    "Thanks again.",
    "Great response.",
    "Bye for now.",
    "See ya."
  ]
}

# -------------------------
# Build dataset
# -------------------------
X, y = [], []
for intent, queries in TRAINING_DATA.items():
    for q in queries:
        X.append(q)
        y.append(intent)

# -------------------------
# Split dataset
# -------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# -------------------------
# ML Pipeline
# -------------------------
clf = Pipeline([
    ("tfidf", TfidfVectorizer(ngram_range=(1,2), stop_words="english")),
    ("logreg", LogisticRegression(max_iter=200, solver="lbfgs"))
])

clf.fit(X_train, y_train)

# -------------------------
# Evaluate
# -------------------------
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))

# -------------------------
# ENTITY DATABASE
# -------------------------
MATERIALS = [
    "steel", "aluminum", "copper", "diamond", "glass", "plastic", "titanium", 
    "magnesium", "iron", "graphene", "silicon", "gold", "platinum", "nickel","CNT"
]

PROPERTIES = [
    "hardness", "yield strength", "strength", "thermal conductivity", "density", 
    "elastic modulus", "poisson", "melting point", "band gap", "refractive index",
    "corrosion", "fatigue", "toughness", "ductility", "conductivity"
]

ENVIRONMENTS = [
    "seawater", "aerospace", "vehicle", "energy storage", "acidic environment",
    "coastal areas", "turbines", "construction", "implants"
]

# -------------------------
# ENTITY EXTRACTION
# -------------------------
def extract_entities(query: str) -> Dict[str, Any]:
    query_lower = query.lower()

    # Find materials
    found_materials = [m for m in MATERIALS if m in query_lower]

    # Find properties
    found_properties = [p for p in PROPERTIES if p in query_lower]

    # Find environments
    found_env = [e for e in ENVIRONMENTS if e in query_lower]

    # Extract numbers (geometry, values)
    numbers = re.findall(r"\d+\.?\d*\s*(?:mm|cm|m|°c|c|g|kg|years|cycles)?", query_lower)

    return {
        "materials": found_materials,
        "properties": found_properties,
        "environment": found_env,
        "geometry_or_values": numbers
    }

# -------------------------
# UNIFIED ENGINE
# -------------------------
def analyze_query(query: str) -> Dict[str, Any]:
    # Intent classification
    proba = clf.predict_proba([query])[0]
    classes = clf.classes_
    best_idx = proba.argmax()
    intent = classes[best_idx]
    confidence = proba[best_idx]

    # Entity extraction
    entities = extract_entities(query)

    return {
        "query": query,
        "intent": intent,
        "confidence": round(float(confidence), 3),
        "entities": entities,
    }

# -------------------------
# Demo
# -------------------------
if __name__ == "__main__":
    samples = [
        "What is the thermal conductivity of CNT?",
        "Steel vs aluminum strength.",
        "Will aluminum corrode in seawater?",
        "Explain crystallography.",
        "How is steel made?",
        "Show me latest research in materials science.",
        "Hello MatBot!"
    ]
    for s in samples:
        print(f"\n{analyze_query(s)}\n")
